# Generated by Django 5.0.6 on 2025-02-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produk', 'verbose_name_plural': 'Produk'},
        ),
        migrations.AddField(
            model_name='product',
            name='kategori',
            field=models.CharField(choices=[('Elektronik', 'Elektronik'), ('Pakaian', 'Pakaian'), ('Makanan', 'Makanan'), ('Minuman', 'Minuman'), ('Lainnya', 'Lainnya')], default='Lainnya', max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='product',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Produk Digital'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Gambar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nama Produk'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Harga (Rp)'),
        ),
    ]
