# Generated by Django 5.0.6 on 2025-03-27 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_customer_email_alter_customer_name_and_more'),
    ]

    operations = [
    ]
