"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'z+ksf@)0d^qojbh4rnp4b1to$hq&*tt(3bs$gf(3i267g$k9ln'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']

# Application definition
INSTALLED_APPS = [
    'admin_interface',
    'colorfield',  # dependency for admin_interface
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    
    # Local apps
    'store.apps.StoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Untuk internationalization
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.i18n',  # Untuk internationalization
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'

# Database Configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db.ecomcu',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'sql_mode': 'STRICT_TRANS_TABLES',
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ===========================
# INTERNATIONALIZATION (BAHASA INDONESIA)
# ===========================

# Bahasa default
LANGUAGE_CODE = 'id'  # Indonesian

# Zona waktu Indonesia
TIME_ZONE = 'Asia/Jakarta'

# Enable internationalization
USE_I18N = True

# Enable localization (format angka, tanggal sesuai lokal)
USE_L10N = True

# Use timezone-aware datetimes
USE_TZ = True

# Bahasa yang tersedia
LANGUAGES = [
    ('id', 'Bahasa Indonesia'),
    ('en', 'English'),
]

# Direktori untuk file translation
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Format tanggal dan waktu dalam Bahasa Indonesia
DATE_FORMAT = 'd F Y'  # 25 Desember 2024
TIME_FORMAT = 'H:i'    # 14:30
DATETIME_FORMAT = 'd F Y H:i'  # 25 Desember 2024 14:30

# Format angka (gunakan titik untuk ribuan, koma untuk desimal)
USE_THOUSAND_SEPARATOR = True
THOUSAND_SEPARATOR = '.'
DECIMAL_SEPARATOR = ','

# ===========================
# STATIC FILES CONFIGURATION
# ===========================

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# ===========================
# MEDIA FILES CONFIGURATION
# ===========================

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ===========================
# MIDTRANS PAYMENT CONFIGURATION
# ===========================

# Production Settings
MIDTRANS_MERCHANT_ID = ''
MIDTRANS_CLIENT_KEY = ''
MIDTRANS_SERVER_KEY = ''
MIDTRANS_IS_PRODUCTION = True #false untuk sandbox
MIDTRANS_BASE_URL = 'https://app.midtrans.com/snap/v1/transactions'

# Default Auto Field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ===========================
# SESSION CONFIGURATION
# ===========================

SESSION_COOKIE_AGE = 86400  # 24 jam
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# ===========================
# CACHE CONFIGURATION
# ===========================

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# ===========================
# EMAIL CONFIGURATION
# ===========================

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# ===========================
# LOGGING CONFIGURATION
# ===========================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'store': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

# ===========================
# FILE UPLOAD SETTINGS
# ===========================

FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5 MB
FILE_UPLOAD_PERMISSIONS = 0o644
DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5 MB

# ===========================
# CUSTOM SETTINGS FOR STORE APP
# ===========================

CART_SESSION_ID = 'cart'
CART_SESSION_TIMEOUT = 3600  # 1 jam

# ===========================
# ADMIN INTERFACE CONFIGURATION
# ===========================

X_FRAME_OPTIONS = 'SAMEORIGIN'

# ===========================
# MESSAGE FRAMEWORK (BAHASA INDONESIA)
# ===========================

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info', 
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# Custom message texts dalam Bahasa Indonesia
MESSAGE_LEVEL = messages.INFO

# ===========================
# SECURITY SETTINGS
# ===========================

if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_REDIRECT_EXEMPT = []
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    ALLOWED_HOSTS = ['yourdomain.com', 'www.yourdomain.com']
else:
    INTERNAL_IPS = [
        '127.0.0.1',
        'localhost',
    ]

# ===========================
# CURRENCY SETTINGS (RUPIAH)
# ===========================

# Default currency symbol
DEFAULT_CURRENCY = 'IDR'
CURRENCY_SYMBOL = 'Rp'

# Number formatting untuk Rupiah
NUMBER_GROUPING = 3
USE_THOUSAND_SEPARATOR = True